CREATE TABLE usuarios (
                          id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome    VARCHAR(255) NOT NULL UNIQUE,
                          senha   VARCHAR(255) NOT NULL,
                          idade   INTEGER,
                          role    VARCHAR(20)  NOT NULL,
                          status  VARCHAR(20)
);

CREATE TABLE clientes (
                          id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nome        VARCHAR(255) NOT NULL UNIQUE,
                          cpf         VARCHAR(11)  NOT NULL UNIQUE,
                          telefone    VARCHAR(20)  NOT NULL,
                          cep         VARCHAR(9)   NOT NULL,
                          logradouro  VARCHAR(255),
                          bairro      VARCHAR(255),
                          cidade      VARCHAR(255)
);

CREATE TABLE veiculos (
                          id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          marca   VARCHAR(255) NOT NULL,
                          modelo  VARCHAR(255) NOT NULL,
                          placa   VARCHAR(7)   NOT NULL UNIQUE,
                          status  VARCHAR(20)  NOT NULL
);