CREATE TABLE romaneios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data        DATE
);

CREATE TABLE produto (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(255) NOT NULL UNIQUE,
    preco       DOUBLE PRECISION,
    romaneio_id BIGINT,
    CONSTRAINT fk_produto_romaneio FOREIGN KEY (romaneio_id) REFERENCES romaneios(id)
);

