CREATE TABLE romaneios
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data       DATE,
    usuario_id BIGINT NOT NULL,
    veiculo_id BIGINT NOT NULL,
    CONSTRAINT fk_romaneio_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_romaneio_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos (id)
);

CREATE TABLE produto
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(255) NOT NULL UNIQUE,
    preco       DOUBLE PRECISION,
    romaneio_id BIGINT,
    CONSTRAINT fk_produto_romaneio FOREIGN KEY (romaneio_id) REFERENCES romaneios (id)
);


CREATE TABLE romaneio_cliente
(
    romaneio_id BIGINT NOT NULL,
    cliente_id  BIGINT NOT NULL,
    PRIMARY KEY (romaneio_id, cliente_id),
    CONSTRAINT fk_rc_romaneio FOREIGN KEY (romaneio_id) REFERENCES romaneios (id),
    CONSTRAINT fk_rc_cliente FOREIGN KEY (cliente_id) REFERENCES clientes (id)
);